### ISSUE TITLE
Ignore Globs don't work from command line

### ISSUE THREAD

**Issue by niieani** [isaacs/rimraf#108]
Example:

Directory `test` has 2 files:
- `a.json`
- `b.txt`

Executing:
```shell
rimraf '!test/**.json' 'test'
```

Results in deleting the whole `test` directory. Command line parameters seem to be treated as separate invocations of rimraf instead of together, like when calling the non-CLI version.

**Comment by isaacs** [comment]
There's a lot going on here!

First, "ignore globs" haven't been supported by node-glob for quite a long time now.  The globs on the command line are additive, so there's no way that one will affect another.

I'm not sure what's going on with the `test/**.json` here, since that's exactly equivalent to `test/*.json`.  If you mean for it to descend into arbitrary child directories, then you'd have to do `test/**/*.json`.  Using a double-star in this way is a little bit confusing, because your intent isn't clear, so I recommend avoiding that style.

So, the first one matches literally nothing (unless you had a folder called `!test` with json files directly in it.)  The second one matches the `test` folder.

Note that anything that is matched will end up having all of its children removed, no matter what.  So, since `test` matches the `test` folder, a file at `test/foo.json` will definitely be removed.  There's no way to remove the `test` folder _without_ removing `test/foo.json`, so I'm guessing that you in fact _want_ the test folder to still be there after the command.

Perhaps this is closer to what you're trying to do?

```
rimraf 'test/!(*.json)'
```

As far as I can tell, rimraf is working as designed, and behaving exactly like the `rm -rf` unix command.

**Comment by niieani** [comment]
OK, indeed the mistake was the double asterisk, which meant that glob "ate" the root dir. However, even with only one asterisk, the ignore glob wasn't working. I found out that the ignore globs work fine with the `del-cli` package, so I've just switched to that instead of `rimraf`. 

```shell
rimraf 'test' '!test/*.json'  # behaves incorrectly: removes 'test', ignore doesn't work
del 'test' '!test/*.json'  # behaves correctly: removes all files inside of 'test' except for .json files.
```
