### ISSUE TITLE
CLI recursive file glob

### ISSUE THREAD

**Issue by aaronbeall** [isaacs/rimraf#135]
I want to remove all files matching `*.css` in all directories and sub-directories, recursively. I tried this:
```
rimraf src/**/*.css
```

And found that it did delete all the `*.css` files in sub-directories of `src` (ex `src/styles/foo.css` but *not* in sub-sub-directories beyond that (ex `src/styles/foo/bar.css`). Strangely, if I run the above command *twice* then the *second* time it deletes what's left in sub-sub-directories.

**Comment by isaacs** [comment]
The shell is expanding the pattern.  Your shell is either an older version of Bash (like the Bash 3 that ships by default on many systems) or does not have the `globstar` shopt set.

One solution is to upgrade to Bash 4, and add `shopt -s globstar` to your `.bashrc` file.

Another is to put quotes around the argument, so that node-glob will expand the pattern for you.
