### ISSUE TITLE
Glob parens not valid

### ISSUE THREAD

**Issue by rcollette** [isaacs/rimraf#137]
This is a valid glob
```
src/*.+(js|map)
```
[globtester](http://www.globtester.com/#p=eJwrLkrW19LT1sgqrslNLNAEACaEBOM%3D&r=eJyzScksU0jOSSwutlXKTSxJzlCyKy5K1i%2FOz00tycjMS9fLKrbRB6qxsyGkMDexAFMlRFGFXgkWU5TsbJKK7MgTBwAIsj5K&)

But I get an error when using parens
```
> rimraf src/**/*.+(js|map)

sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `rimraf src/**/*.+(js|map)'

```

**Comment by shodanuk** [comment]
Not sure if you're having the same issue but I had to wrap glob pattern in quotes to get it to work in an npm script:

```
"prebuild": "rimraf public/+(js|css)/*.+(js|css)"
```

**Comment by isaacs** [comment]
Globs removed in v4.  It'll just delete exactly whatever shell expansion gives it.

**Comment by Kasthoori** [comment]
After upgrading rimraf 4.2.1 following issue detected. In E2E testing node_modules/rimraf/dist/cjs/src/ignore-enoent.js 
if(er?.code !== 'ENOENT') 
. show as error SyntaxError: Unexpected token .

**Comment by isaacs** [comment]
@Kasthoori Your problem is not relevant to this issue.  Please post a new issue when you have a new problem, rather than commenting on one posted years ago which has been closed.

Be sure to include the version of node you are using, and ensure that it is within the range supported by this module's `engines` field (ie, >= 14).
