### ISSUE TITLE
HowTo: delete specific folders/files

### ISSUE THREAD

**Issue by TheoMer** [isaacs/rimraf#148]
So I wish to delete specific resources from within my build folder, public, At the moment within my package.json I am doing the following:

```
"clean": "rimraf public",
```

which of course delete the entire directory. Is it possible to only delete all instances of *.js files or another directory within this directory, for example?

**Comment by ash0080** [comment]
rimraf foldername/*

**Comment by rhernandog** [comment]
If you want to clean multiple targets just use a space between them. For example if you need to clear the **js** folder and also the **index.html** file of a typical webpack set up, you can use this command:

```
rimraf build/js/* build/index.html
```

That will remove the files in the js folder and the index.html file in the root of build:
```
|- build
|- build/index.html
|- build/js/*.js
```

**Comment by thecodecafe** [comment]
@rhernandog how can I delete from within a JS file?
Tried this but nothing happend.
```````````````````````````````````
rimraf('directory', {
    disableGlob: true
}, function(){
     /* do nothing */ 
});
```````````````````````````````````

**Comment by rhernandog** [comment]
@thecodecafe To be completely honest I haven't been working on Node for a while, I used rimraf manly when working with webpack to clean the dist folder and since version 4 of webpack I've been using the clean webpack plugin, so I haven't been too much into this particular package in the last 6 months.

Have you tried getting the folder first using the sync read folder method from FS?. Also have you tried without the `disableGlob` option?, you know just remove all the folder?.

Maybe you're not getting the route to the folder correctly.

I'll whip a small folder and try your code and see what happens, you just caught me without a lot of time.

**Comment by aliskhanoff** [comment]
rimraf public/**/*.*

**Comment by isaacs** [comment]
Try this:

```js
@rhernandog how can I delete from within a JS file?
Tried this but nothing happend.

const rimraf = require('rimraf');

rimraf('directory', {
    disableGlob: true
}, function(er){
    if (er) {
        console.error('it did not work, here is the reason:', er)
    } else {
        console.log('it worked!', require('fs').existsSync('directory')
    }
});
```
