### ISSUE TITLE
No proper examples

### ISSUE THREAD

**Issue by villan106** [isaacs/rimraf#180]
No proper examples for code for delete the folder.  just content only there.

please provide the proper examples

**Comment by helgatheviking** [comment]
Hardly a proper example because I only found this 5 minutes ago, but so far I have been able to get

`rimraf assets/js/*` to delete all files in the JS folder relative to my current path

and

`rimraf assets/js` to delete the entire `js` folder... again relative to current path.

and

`rimraf %npm_package_assets_js%`

where the variable is defined in the `package.json` like so:

```
  "assets": {
    "js": "assets/js/*.js"
  },
```
to all remove files. Hope it helps someone.
