### ISSUE TITLE
rimraf dist/**/*.map doesn't delete in dist, only in subfolders

### ISSUE THREAD

**Issue by michael-brade** [isaacs/rimraf#191]
Hi, I want to delete all my `.js.map` files recursively in `dist`. This works:
```
cd dist
rimraf **/*.js.map
```
This, however, does not delete the files `dist/*.js.map`, it deletes only in subdirectories of `dist`:
```
rimraf dist/**/*.js.map
```

**Comment by michael-brade** [comment]
I just discovered that this works:
```
rimraf dist/**.js.map
```

**Comment by michael-brade** [comment]
Oops, I take my last comment back, `**.js.map` does NOT descend into subdirectories. My bad.

**Comment by isaacs** [comment]
My guess is that your shell is interpreting the `**` and expanding it as if it was `*`, so rimraf never sees the glob (which is the default behavior in bash).  It likely works the first way because no file matches `*/*.js.map`, so the shell passes the unexpanded glob, which rimraf interprets properly.

Try this:  `rimraf "dist/**/*.js.map"`

**Comment by michael-brade** [comment]
Gee, I should have thought of that! Yes, you are right, that works :) Thanks!
