### ISSUE TITLE
npx rimraf: Fails with "The system cannot find the path specified."

### ISSUE THREAD

**Issue by JasonGore** [isaacs/rimraf#233]
I think I've found an issue with rimraf that reproduces with `npx` (Node v16) and a `jest` installation on multiple Windows 10 computers:

```txt
λ npx rimraf node_modules
The system cannot find the path specified.
```

I've got a [basic repro](https://github.com/JasonGore/rimraf-repro):

Steps to repro

1. clone repo
1. run `yarn`
1. run `npx rimraf node_modules`

May be specific to version of Node installed. It happens with node v16.13.1 but does not happen with v14.17.3.

**Comment by tomosterlund** [comment]
I think there is something temporarily up. Just a few days ago, I built a bunch of Docker images using the `node:14-alpine` image, which uses Node 14.18.2. This always worked well with rimraf. As I tried building the same images with the same config and environment as always, just 10 minutes ago, I got a bunch of errors saying that npm could not find some dependencies in `/node_modules/.staging/`.

For me, upgrading to `node:16-alpine` solved the error (Node version 16.13.1).

**Comment by JasonGore** [comment]
I see the issue with both Node version 16.13.0 and 16.13.1 using the repro I provided above.

**Comment by hamilton-lima** [comment]
Tested with node:14.17.3-alpine3.14 and got the same error

```
 > [development 6/6] RUN npm run build:
#13 1.055
#13 1.055 > forms@0.0.1 prebuild /usr/src/app
#13 1.055 > rimraf dist
#13 1.055
#13 1.058 sh: rimraf: not found
```

**Comment by hamilton-lima** [comment]
Upgrading to node:16.13.2-alpine3.15 fixed the issue.

**Comment by seanblonien** [comment]
I just switched to using `deli-cli` because this issue kept happening in a script

**Comment by isaacs** [comment]
If you've installed rimraf, you should have a bin available at `./node_modules/.bin/rimraf`. If it's not being placed there, then the install didn't work. That's an npm bug, most likely.

If you're trying to use that bin to delete `node_modules`, then that's liable to fail 100% of the time on some systems, because it's trying to delete files that are currently open and locked.  (It should actually work fine on most posix systems, but this will be an issue on Windows, and there's really nothing that can be done about it.)

If you have `rimraf` as a dep, then `npx rimraf` will use the one from node_modules, so that's going to get you into that situation.  First remove rimraf from your dependencies with `npm rm rimraf`, and then `npx -y rimraf node_modules` should work fine.
