### ISSUE TITLE
Callback invoked with `null` if no targets found

### ISSUE THREAD

**Issue by Zsar** [isaacs/rimraf#237]
Calling `rimraf('dist', error => console.error("Could not delete 'dist' folder: '" + error + "'\n"))` without `dist` folder will print "Could not delete 'dist' folder: 'null'".

One has to write `rimraf('dist', error => error && console.error("Could not delete 'dist' folder: '" + error + "'\n"))` instead.

According to documentation "If the file doesn't exist, rimraf will return successfully, since your desired outcome is already the case."

I'd expect no error in this case (not even `null`). - Is this a reasonable expectation? _If not_, should the error not be non-`null`?

https://github.com/isaacs/rimraf/blob/9219c937be159edbdf1efa961f2904e863c3ce2d/rimraf.js#L77-L78

**Comment by isaacs** [comment]
It is not a reasonable expectation.

It will always return.  If the error is set to some Error value, then it means a problem happened, and the file(s) could not be deleted.  If the error is not set to an Error value, then it means that it's done deleting the file(s) specified.

This is the same as all Node.js-style callbacks.  For example, `fs.unlink('file.txt', (err) => { /* if err is an Error, it wasn't deleted.  if err is null, then it was deleted, and should be gone now. */ })`

Otherwise how would you know when it's done deleting?  It doesn't return a Promise.
