### ISSUE TITLE
Double asterisk as a folder is not recursive

### ISSUE THREAD

**Issue by z164** [isaacs/rimraf#240]
`npx rimraf ./folderName/**/*.ext"`

Double asterisk as a folder is not recursive. Seems like it goes only one level deep in `folderName`

with file structure of 
```
folderName
├── rootfile.ext
└── someFolder
    ├── otherFolder
    │   └── anything.ext
    └── something.ext
```

would only delete `rootfile.ext`.

Unix `rm rf ./foldername/**/*.ext` working as expected cleaning all of the `.ext` files

Package version: `3.0.2`
Node version: `18.3.0`

**Comment by z164** [comment]
Interesting thing that it works correctly if invoked from cli directly. But if you exec it from child_process it does not work

**Comment by isaacs** [comment]
Are you quoting the argument?  If not, it's just the shell expansion.  Ie, `exec('rimraf ./foldername/**/*.ext')` is not the same as `exec('rimraf "./foldername/**/*.ext"')`, because `exec` is `sh -c ${argument}`.

If you're on your regular login shell, you're probably using bash or zsh, with globstar and extglob enabled.  So if you don't quote the argument, the shell expands the globstar, and actually invokes `rimraf ./foldername/someFolder/something.ext ./foldername/someFolder/otherFolder/anything.ext`.  If you do quote the argument, then rimraf sees `'./foldername/**/*.ext'` as the only thing in argv, and does the glob expansion itself using the `glob` module.

But!  If you're invoking `sh` instead of `zsh` or `bash`, well, it doesn't know what globstar is.  In `sh`, `**` is just the same thing as `*`.  So _it_ expands the argument to just `./foldername/someFolder/something.ext`, and doesn't see any other matches.

I hope that helps explain what's going on.  Lmk if I missed something.
