### ISSUE TITLE
Do more testing instead of releasing as is

### ISSUE THREAD

**Issue by paulmillr** [isaacs/rimraf#252]
Just a heads up: 9 releases in 5 days isn't great. Try doing more testing and fitting it into 2-3 releases instead in the future. 

The dependabot crap spams thousands of github repos with pull requests upgrading rimraf. I of course disable it, but unfortunately after the spam.

**Comment by isaacs** [comment]
This may seem harsh, or come across as rude, but I feel strongly that it is important to be very clear about this boundary.

No, I'm going to keep releasing stuff as I see fit. If someone finds a bug, I'll fix it, and release a patch immediately, because that's satisfying and fun. I suggest limiting your deps with reasonable semver ranges to avoid pulling in major version updates until you're ready, or configure your dependency update checks to batch weekly, or configure your email client to send all such messages to a folder that you check periodically.

My work on this project is free labor done for the fun of it. The contract of open source is that producers do whatever they feel like, and if you find the results useful, you're welcome. But if we haven't entered into some other kind of contract, for example one where you pay me for consenting to some arbitrary terms you set, you don't get to tell me how to run things. No guarantees of fitness for a specific purpose, distributed as-is, etc.

It's fine to request things, even unreasonable things, and I'm not offended by the suggestion. But the answer is no. 

It is somewhat presumptuous to assume that I have not tested this library extensively prior to releasing it. Hybrid typescript module distribution is a rats nest of edge cases, and getting the pattern exactly right, for multiple combinations of bundlers, ts versions, module environments, etc., is nearly impossible without having to make edits to correct the issues that arise.

I know you probably also do not intend any offense with your request, and I've been doing this long enough to have a thick skin and recognize most people mean well. Nevertheless, I'd encourage you to consider that requests/criticisms like this one impose excess emotional labor on open source producers. Making the process less fun means less incentive to provide open source software development labor, which means less value being added to the commons for everyone.

**Comment by paulmillr** [comment]
Thanks, Isaacs.

P.S. we're in the same boat.

**Comment by isaacs** [comment]
I know you're good people, I just try to make this point super clear every time.  Feel free to copy this statement any time you need to push back on similar requests ;)
