### ISSUE TITLE
fillNegs() Error

### ISSUE THREAD

**Issue by xiaoMingLong** [isaacs/rimraf#265]
**node version 12.22.12** 

D:\Github\vue-openlayer-api-main>rimraf node_modules
C:\Users\Administrator\AppData\Roaming\npm\node_modules\rimraf\node_modules\minimatch\dist\cjs\ast.js:86
    #fillNegs() {
             ^

SyntaxError: Unexpected token '('
[90m    at wrapSafe (internal/modules/cjs/loader.js:915:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:963:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:863:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:708:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:887:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\[4mrimraf[24m\node_modules\[4mminimatch[24m\dist\cjs\index.js:9:18)
[90m    at Module._compile (internal/modules/cjs/loader.js:999:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)[39m

![image](https://user-images.githubusercontent.com/91582283/230704118-097fcf0f-5e97-415c-a781-fa078b340d4d.png)

**Comment by isaacs** [comment]
That node version is not supported. As specified in the package.json, node 14 or higher is required. Upgrade node, or downgrade rimraf.

**Comment by intelligentCoding** [comment]
I am have the same issue although i am using Node: 18

**Comment by abinhho** [comment]
> I am have the same issue although i am using Node: 18


> Then it's not the same issue

My case: It was not related to node version. Updated firebase CLI resolved the issue. 
Maybe someone using a cli (whatever services) then try to upgrade it.

**Comment by ukhanzada-nisum-com** [comment]
Has anyone solved this.. I am facing the same issue with Node 14.

**Comment by isaacs** [comment]
@abinhho Does fire base run code remotely on google's servers? Isn't that the whole point of it? So if YOUR machine is using node 18, it doesn't much matter, if THEIR machines aren't.

The best approach is to `console.log(process.version)` in the actual process that's crashing, and verify the output along with the error message from the crash, so you can verify that it's actually running on the node you think it is.

**Comment by isaacs** [comment]
@ukhanzada-nisum-com as mentioned previously, if you are using a supported node version then what you have is not "the same" issue, because "the issue" here is that the version of node used didn't support private field syntax. 

So either you have a different issue, or you're not using the node version you think you are. Please verify your node version by logging it in the program that is crashing, like, the same exact code path. If it IS indeed a supported version, then your error message will be different. (I suppose you could have node 14 spawn a node 12 process that somehow encounters this code, but that seems less likely.)

If it's a different problem, post a new issue. If it's the same problem, upgrade node. If you think it's the same problem on a different version of node that doesn't have this problem, idk what to tell you, that's just incorrect.

**Comment by q2333gh** [comment]
> That node version is not supported. As specified in the package.json, node 14 or higher is required. Upgrade node, or downgrade rimraf.

I was like an ape in the Space Odyssey . thank you ! it help a lot !

**Comment by scripting** [comment]
I'm trying to figure out why all of a sudden my Node app is getting caught in this error, and what I have to change to get my app to run again. 

When did this requirement for Node 14 go in?
