### ISSUE TITLE
Loop twice in rimraf-window when interactive mode

### ISSUE THREAD

**Issue by yuningjiang123** [isaacs/rimraf#267]
On windows, when using rimraf in interactive mode like this:
`rimraf dir -i`
Suppose there are two files inside dir: dir/a and dir/b. If you tap 'no' to all prompts, the terminal will print like this:

`
rm? dir/a
[(Yes)/No/All/Quit] > n
rm? dir/b
[(Yes)/No/All/Quit] > n
rm? dir/a
[(Yes)/No/All/Quit] > n
rm? dir/b
[(Yes)/No/All/Quit] > n
`

Each file that is confirmed as 'No' will be prompt again.

There is no this issue on linux/mac.

**Comment by isaacs** [comment]
Ahh, I think I know why that is.  On windows, sometimes files just don't delete in time, so you end up with an `ENOTEMPTY` error when you try to remove the directory.  Then it tries again, using a more reliable (but slower) technique.  So it's retrying because the file is still present after the first pass, and still keeping the same prompt filter.  It should keep track of which files and directories were skipped, and not try to remove directories if they have skipped children.

**Comment by isaacs** [comment]
I can't for the life of me figure out how to reproduce this.  Does it still happen on the latest release?  Are there more steps in the repro that I'm missing?
