### ISSUE TITLE
Installation requires global typescript

### ISSUE THREAD

**Issue by mhudasch** [isaacs/rimraf#278]
I am installing rimraf 5.0.1 using npm 9.5.1 which executes the prepare script after installation.
The prepare script requires a global (available in PATH) typescript or tsc installation.
Since I as a package consumer don't know which typescript version is required to run the prepare script this should not be globally required to assure a deterministic outcome.

**Comment by isaacs** [comment]
npm does not run the prepare script as part of installation, normally. It runs prepare as part of an installation from a git repo, but prior to running the prepare script, it runs an install of the dev dependencies, so that should provide typescript 5.0.4 in the temporary git checkout directory in the npm cache.

```

$ pwd
/tmp/rimraf-278

$ ls -laF
total 0
drwxr-xr-x  2 isaacs  wheel   64 Jun 12 12:27 ./
drwxrwxrwt  7 root    wheel  224 Jun 12 12:24 ../

$ echo {} > package.json

$ npm -v
9.5.1

$ npm i rimraf@5.0.1

added 41 packages, and audited 42 packages in 407ms

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ npm ls rimraf
rimraf-278@ /private/tmp/rimraf-278
└── rimraf@5.0.1


$ npm ls typescript
rimraf-278@ /private/tmp/rimraf-278
└── (empty)


$ which tsc

$ tsc
-bash: tsc: command not found
```

Please share the command you are running and the actual error encountered.

**Comment by mhudasch** [comment]
Year sorry. After a complete clean re-install I could not reproduce my issue. 
Thank you.
